v 0.1
Vladosik12333/project-4-filmoteka pull request #10
Opened 2021-11-22 15:23 UTC by rostunho

switching headers
common buttons

2021-11-22 16:03 UTC, Svitlana-Ilnytska reviewed
все чудово, тільки одненька буковка

2021-11-22 16:03 UTC, Svitlana-Ilnytska commented on src/sass/layouts/_header.scss
> +    screen and (min-resolution: 192pi) and (min-width: 769px),
здається пропущена одна буква 'dpi'

2021-11-22 16:49 UTC, rostunho commented on src/sass/layouts/_header.scss
> +    screen and (min-resolution: 192pi) and (min-width: 769px),
Виправив.

2021-11-22 17:25 UTC, Yurii97 approved these changes, later dismissed

2021-11-22 18:49 UTC, Svitlana-Ilnytska approved these changes, later dismissed

2021-11-22 20:49 UTC, Vladosik12333 requested changes

2021-11-22 20:49 UTC, Vladosik12333 commented on src/partials-html/header.html
> +        <span class="logo__item">Filmoteka</span>
h1

2021-11-22 20:49 UTC, Vladosik12333 commented on src/partials-html/header.html
> +            <a class="nav__link nav__link--current" href="#" id="home">Home</a>
home-js

2021-11-22 20:49 UTC, Vladosik12333 commented on src/js/header-switching.js
> +  libraryPageBtn: document.querySelector('#my-library'),
library-js

2021-11-22 20:49 UTC, Vladosik12333 commented on src/js/header-switching.js
> +  homePageBtn: document.querySelector('#home'),
home-js

2021-11-22 20:49 UTC, Vladosik12333 commented on src/partials-html/header.html
> +    <!-- input -->
input вище library,
div на form

2021-11-22 20:49 UTC, Vladosik12333 commented on src/partials-html/header.html
> +      <img class="input__icon" src="./images/icons/search.svg" alt="Search icon" />
img на svg

2021-11-22 20:49 UTC, Vladosik12333 commented on src/partials-html/header.html
> +      Search result not successful. Enter the correct movie name and
Зміни сповіщення.

2021-11-22 20:49 UTC, Vladosik12333 commented on src/sass/layouts/_header.scss
> +  &__icon {
delete this

2021-11-22 20:49 UTC, Vladosik12333 commented on src/sass/layouts/_header.scss
> +  // margin-left: auto;
delete

2021-11-22 20:49 UTC, Vladosik12333 commented on src/sass/layouts/_header.scss
> +  border-bottom: 0.5px solid #ffffff;
заміни fffffff

2021-11-22 20:49 UTC, Vladosik12333 commented on src/sass/layouts/_header.scss
> +  font-family: Roboto;
Дубль

2021-11-22 20:49 UTC, Vladosik12333 commented on src/sass/layouts/_header.scss
> +  font-style: normal;
Дубль

2021-11-22 20:49 UTC, Vladosik12333 commented on src/sass/layouts/_header.scss
> +  font-weight: normal;
Дубль

2021-11-22 20:49 UTC, Vladosik12333 commented on src/sass/layouts/_header.scss
> +  font-family: Roboto;
Дубль

2021-11-22 20:49 UTC, Vladosik12333 commented on src/sass/layouts/_header.scss
> +  font-style: normal;
Дубль

2021-11-22 20:49 UTC, Vladosik12333 commented on src/sass/layouts/_header.scss
> +  font-weight: normal;
Дубль

2021-11-22 20:49 UTC, Vladosik12333 commented on src/sass/layouts/_header.scss
> +  font-family: Roboto;
Дубль

2021-11-22 20:49 UTC, Vladosik12333 commented on src/sass/layouts/_header.scss
> +  font-style: normal;
Дубль

2021-11-22 20:49 UTC, Vladosik12333 commented on src/sass/layouts/_header.scss
> +  font-weight: normal;
Дубль

2021-11-22 20:49 UTC, Vladosik12333 commented on src/partials-html/header.html
> +      <input type="text" class="input__query" id="input" placeholder="Поиск фильмов" />
+ autofocus

2021-11-22 21:38 UTC, rostunho commented on src/partials-html/header.html
> +        <span class="logo__item">Filmoteka</span>
Є.

2021-11-22 21:39 UTC, rostunho commented on src/partials-html/header.html
> +            <a class="nav__link nav__link--current" href="#" id="home">Home</a>
+

2021-11-22 21:40 UTC, rostunho commented on src/js/header-switching.js
> +  libraryPageBtn: document.querySelector('#my-library'),
+

2021-11-22 21:40 UTC, rostunho commented on src/js/header-switching.js
> +  homePageBtn: document.querySelector('#home'),
Є.

2021-11-22 21:41 UTC, rostunho commented on src/partials-html/header.html
> +    <!-- input -->
Є.

2021-11-22 21:46 UTC, rostunho commented on src/partials-html/header.html
> +      <img class="input__icon" src="./images/icons/search.svg" alt="Search icon" />
Є.

2021-11-22 21:48 UTC, rostunho commented on src/partials-html/header.html
> +      Search result not successful. Enter the correct movie name and
Є.

2021-11-22 21:53 UTC, rostunho commented on src/sass/layouts/_header.scss
> +  &__icon {
Є.

2021-11-22 21:55 UTC, rostunho commented on src/sass/layouts/_header.scss
> +  // margin-left: auto;
Є.

2021-11-22 21:56 UTC, rostunho commented on src/sass/layouts/_header.scss
> +  border-bottom: 0.5px solid #ffffff;
Замінивю

2021-11-22 21:58 UTC, rostunho commented on src/sass/layouts/_header.scss
> +  font-family: Roboto;
Про всяк випадок поставив inherit.

2021-11-22 21:59 UTC, rostunho commented on src/sass/layouts/_header.scss
> +  font-style: normal;
inherit

2021-11-22 21:59 UTC, rostunho commented on src/sass/layouts/_header.scss
> +  font-weight: normal;
+

2021-11-22 22:00 UTC, rostunho commented on src/sass/layouts/_header.scss
> +  font-family: Roboto;
inherit

2021-11-22 22:00 UTC, rostunho commented on src/sass/layouts/_header.scss
> +  font-weight: normal;
inherit

2021-11-22 22:00 UTC, rostunho commented on src/sass/layouts/_header.scss
> +  font-family: Roboto;
Є.

2021-11-22 22:00 UTC, rostunho commented on src/sass/layouts/_header.scss
> +  font-style: normal;
Є.

2021-11-22 22:00 UTC, rostunho commented on src/sass/layouts/_header.scss
> +  font-weight: normal;
Є.

2021-11-22 22:02 UTC, rostunho commented on src/partials-html/header.html
> +      <input type="text" class="input__query" id="input" placeholder="Поиск фильмов" />
Є.

2021-11-23 13:18 UTC, Vladosik12333 approved these changes

2021-11-23 13:19 UTC, merged