first step
Vladosik12333/project-4-filmoteka pull request #2
Opened 2021-11-19 18:33 UTC by VitaliiKarpovets

2021-11-19 18:46 UTC, Vladosik12333 commented
На Stund Up.

2021-11-19 18:47 UTC, Vladosik12333 requested changes, later dismissed
На Stund Up.

2021-11-21 21:01 UTC, Yurii97 reviewed
Внести правки

2021-11-21 21:01 UTC, Yurii97 commented on src/templates/card-gallery.hbs
> +  <li class='card'>
добавити дата атрибут! Обговорювали після зборів

2021-11-21 21:01 UTC, Yurii97 commented on src/sass/components/_gallery.scss
> +  background-color: #ffffff;
вставляємо колір зі змінних :  

// акцентний помаранчевий:
$accentColort: #ff6b08;

// текст
$textLightColor: #ffffff;
$textDarkColor: #000000;

// підкладка під фон:
$bgOverlayColor: rgba(0, 0, 0, 0.56);

// фон альтернативний (футер і кнопки світчера)
$bgSecondaryColor: #f7f7f7;

2021-11-21 21:01 UTC, Yurii97 commented on src/sass/components/_gallery.scss
> +  background-color: currentColor;
???
// акцентний помаранчевий:
$accentColort: #ff6b08;

// текст
$textLightColor: #ffffff;
$textDarkColor: #000000;

// підкладка під фон:
$bgOverlayColor: rgba(0, 0, 0, 0.56);

// фон альтернативний (футер і кнопки світчера)
$bgSecondaryColor: #f7f7f7;

2021-11-23 18:39 UTC, Yurii97 approved these changes

2021-11-23 21:09 UTC, rostunho approved these changes
Беремо для тестування живої сторінки. Рефакторимо баг-фіксами.

2021-11-23 21:10 UTC, merged