Feature/modal
Vladosik12333/project-4-filmoteka pull request #6
Opened 2021-11-20 15:53 UTC by topalov92

Добавив верстку модального вікна фільму з стилями

2021-11-20 18:39 UTC, Yurii97 approved these changes, later dismissed

2021-11-21 15:08 UTC, rostunho requested changes
Переконайся, що є всі закриваючі теги </div>.
Інше в коментарях. На зв'язку.

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +<div class="backdrop backdrop-hidden">
Пропонуюу: class="backdrop backdrop--hidden"

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +    <div class="modal-container">
Давай, по БЕМу class="container container--modal". Пізніше перенесу ці стилі в загальний sass-паршал.

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +    <div class="modal-poster-block">
class="film-info__poster-block"

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +        <img src="https://www.themoviedb.org/t/p/w300_and_h450_bestv2/ci5A9TPmNajMxt1L8p4KlZ76sc9.jpg"
class="film-info__poster-image"

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +<div class="flex-container">
class="container container--inner-modal"

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +    <div class="modal-info">
class="film-info__description"

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +        <h2 class="modal-title">A FISTFUL OF LEAD</h2>
class="film-info__title"
Крім того, давай або взагалі приберемо попередній 'h2' (той, який прихований), або тут тоді зробимо 'h3'.

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +            <ul class="modal-infotable">
class="film-info__table"

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +                <li class="item">
class="film-info__table-item"
і в наступних так само

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +                    <p>Vote / Votes</p>
class="film-info__table-line-title"
і в наступних 'p' так само

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +                    <span class="vote">7.3</span>
class="film-info__vote"

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +                    <span class="votes">1260</span>
class="film-info__votes"

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +                    <span class="popularity">100.2</span>
class="film-info__popularity"

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +                    <span class="original-title">A FISTFUL OF LEAD</span>
class="film-info__original-title"

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +                    <ul class="genres-list">
class="film-info__genres-list"

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +                        <li class="genre">Western</li>
class="film-info__genre"

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +        <h3 class="about-title">About</h3>
class="film-info__about-title"

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +        <p class="about-text">Four of the West’s most infamous outlaws assemble to steal a huge stash of gold from the most corrupt settlement of the
class="film-info__about-text"

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +    <ul class="modal-button-list">
class="film-info__button-list"

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +        <li class="modal-btn-item">
class="film-info__button-item"

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +            <button class="modal-btn" type="button" data-modal="watched"">
class="button button--on-modal-is-active"
Кнопка в нас окремий компонент, тому давай поставимо її як блок з модифікатором.

2021-11-21 15:08 UTC, rostunho commented on src/partials-html/modal.html
> +            <button class="modal-btn" type="button" data-modal="queue" ">
class="button button--on-modal"

2021-11-21 15:08 UTC, rostunho commented on src/sass/components/_modal.scss
> +// body.scroll-hidden {
Не забудь "розкоментувати" потрібні рядки.

2021-11-21 15:08 UTC, rostunho commented on src/sass/components/_modal.scss
> +.modal-btn {
Пізніше, перенесу ці властивості в загальний sass-паршал.

2021-11-21 15:08 UTC, rostunho commented on src/sass/components/_modal.scss
> +//   &-hidden {
Давай ще зідзвонимось. Можливо, тут потрібно додати і visibility...

2021-11-21 20:49 UTC, Yurii97 reviewed
Внеси правки

2021-11-21 20:49 UTC, Yurii97 commented on src/sass/components/_modal.scss
> +  display: flex;
.film-info__button-list {
  display: flex;

2021-11-21 20:49 UTC, Yurii97 commented on src/sass/components/_modal.scss
> +  display: flex;
видали! дані стилі

2021-11-21 20:49 UTC, Yurii97 commented on src/partials-html/modal.html
> +    <ul class="film-info__button-list">
<ul class="film-info__button-list"> - заміни клас на "modal-button"

2021-11-21 20:49 UTC, Yurii97 commented on src/sass/components/_modal.scss
> +.film-info__button-list {
Видали

2021-11-22 08:03 UTC, Yurii97 approved these changes

2021-11-22 15:02 UTC, rostunho approved these changes
Беремо в поточну версію проекту. Ще обговоримо оптимізацію.

2021-11-22 15:03 UTC, merged