fix-library
Vladosik12333/project-4-filmoteka pull request #7
Opened 2021-11-20 16:24 UTC by Yurii97

внесено правки згідно зауважень

2021-11-20 21:18 UTC, rostunho requested changes
Загалом все ок. Але я обіцяв "придиратися" до БЕМу :)

2021-11-20 21:18 UTC, rostunho commented on src/partials-html/library-header.html
> +<header class="library-header">
Пропоную по ВАМ: class="header header--library" (блок з модифікатором).

2021-11-20 21:18 UTC, rostunho commented on src/partials-html/library-header.html
> +        <svg>
Я б до <svg> ще докинув class="logo__icon"

2021-11-20 21:18 UTC, rostunho commented on src/partials-html/library-header.html
> +            <a class="nav__link nav__link-current" href="#">my library</a>
class="nav__link nav__link--current" ("--" - як казав Репета, європейський варіант).

2021-11-20 21:18 UTC, rostunho commented on src/partials-html/library-header.html
> +    <div class="varible-nav">
Давай, можливо class="library-nav" ? Це ж навігація бібліотекою. А замість неї будемо class="search" (мій) підставляти.

2021-11-20 21:18 UTC, rostunho commented on src/partials-html/library-header.html
> +          <button id="library-watched" type="button" class="button button__is-activ">
class="button button--is-active" (Як модифікатор, а не елемент. Він же ж тільки колір змінює і не впливає на геометрію. )

2021-11-20 21:18 UTC, rostunho commented on src/sass/components/_buttons.scss
> +    }
Пропоную ще додати модифікатор &--on-modal {} з чорними текстом і рамкою, шоб одразу для модалок було по всій красі.

2021-11-20 21:18 UTC, rostunho commented on src/sass/components/_buttons.scss
> +  }
Давай, ще порадимось:
 - я б ще додав cursor: pointer;
 - і чи будемо якось підсвічувати кнопки при ховері/фокусі ?

2021-11-20 21:18 UTC, rostunho commented on src/sass/layouts/_library-header.scss
> +    button {
Перенеси, будь ласка, ці властивості з селектора тегу в селектор класу. Бо вони зачеплять і кнопки в модалці. А в планшетній і мобільній версіях розміри кнопок в хедері і модалці різні.

2021-11-20 21:26 UTC, Yurii97 commented on src/partials-html/library-header.html
> +    <div class="varible-nav">
Я тут думав - що ми в цей дів будемо перерендер розмітки пхати

2021-11-20 21:28 UTC, Yurii97 commented on src/sass/components/_buttons.scss
> +  }
ховер і фокус - робив кастомно  - робити загальні?

2021-11-20 21:41 UTC, Yurii97 commented on src/partials-html/library-header.html
> +<header class="library-header">
є

2021-11-20 21:41 UTC, Yurii97 commented on src/partials-html/library-header.html
> +        <svg>
є

2021-11-20 21:41 UTC, Yurii97 commented on src/partials-html/library-header.html
> +            <a class="nav__link nav__link-current" href="#">my library</a>
є

2021-11-20 21:42 UTC, Yurii97 commented on src/partials-html/library-header.html
> +    <div class="varible-nav">
є

2021-11-20 21:48 UTC, Yurii97 commented on src/partials-html/library-header.html
> +          <button id="library-watched" type="button" class="button button__is-activ">
є

2021-11-20 21:51 UTC, Yurii97 commented on src/sass/components/_buttons.scss
> +    }
"+"

2021-11-20 21:52 UTC, Yurii97 commented on src/sass/components/_buttons.scss
> +  }
cursor: pointer; - вже є

2021-11-20 22:02 UTC, Yurii97 commented on src/sass/components/_buttons.scss
> +  }
"+"

2021-11-20 22:03 UTC, Yurii97 commented on src/sass/layouts/_library-header.scss
> +    button {
ок! но не зацепить - тег підвязаний до класу батька  :)

2021-11-20 22:14 UTC, Vladosik12333 approved these changes, later dismissed

2021-11-20 22:15 UTC, rostunho commented on src/sass/layouts/_library-header.scss
> +    button {
Каюсь. Не добачив.

2021-11-21 17:53 UTC, rostunho approved these changes
Ок. Беремо в проміжну версію проекту.

2021-11-21 17:53 UTC, rostunho commented on src/sass/layouts/_library-header.scss
> +    max-width: 1024px;
Ok. Беремо цей варіант за поточний. В разі потреби поправимо обидва варіанти хедера через баг-фікси.

2021-11-21 18:08 UTC, Vladosik12333 approved these changes

2021-11-21 18:10 UTC, merged