storage(id)
Vladosik12333/project-4-filmoteka pull request #8
Opened 2021-11-20 19:12 UTC by Yborline

2021-11-20 20:47 UTC, Yurii97 reviewed
Внести правки

2021-11-20 20:47 UTC, Yurii97 commented on src/js/locale-stor.js
> +            localStorage.setItem('watched', array)
?

2021-11-20 20:47 UTC, Yurii97 commented on src/js/locale-stor.js
> +            localStorage.setItem('watched', array)
попробуй в масив запхати обєкт з даними { назва фільму , рік, ссилка на картинку, жанри(масив жанрів), рейтинг}

зданого обєкту зарендерим картку фільму

2021-11-20 20:47 UTC, Yurii97 commented on src/js/locale-stor.js
> +            localStorage.setItem('watched', array)
+ в також id - щоб по ньому можна було знайти всю інфу по фільму(на модальне вікно)

2021-11-20 20:53 UTC, Yurii97 reviewed
+ добав метод класу який повертає масив обєктів

2021-11-23 18:08 UTC, Yurii97 reviewed
виправ - галерея не твій файл

2021-11-23 18:08 UTC, Yurii97 commented on src/js/locale-stor.js
> +        const parseli = localStorage.getItem('watched')
даний метод має повертати parseli

2021-11-23 18:08 UTC, Yurii97 commented on src/js/locale-stor.js
> +        this.getArray.push(JSON.parse(parseli))
це лишнє - перевір - ти масив пхаєш у масив - не потрібно

2021-11-23 18:08 UTC, Yurii97 commented on src/js/locale-stor.js
> +            if (watched.includes(objString)) {
перевірка не працює - потрібно пофіксити

2021-11-23 18:08 UTC, Yurii97 commented on src/js/locale-stor.js
> +           this.getArray = [];
по коду не використовується

2021-11-23 18:08 UTC, Yurii97 commented on src/js/locale-stor.js
> +}
Перевір чи працює мій варіант (пофікшений твій):

2021-11-23 18:08 UTC, Yurii97 commented on src/js/locale-stor.js
> +}
class LocalStorQueue {
    constructor() {   
    }
    saveLocalStorage(obj) {
        const queue = localStorage.getItem('queue');
        const array = []
        if (queue) { 
            if (queue.includes(JSON.stringify(obj))) {
            return alert('такой фильм уже есть')
            }
                const pars = JSON.parse(queue)
                array.push(...pars , obj)
                localStorage.setItem('queue', JSON.stringify(array))
        } else{
                array.push(obj)
                localStorage.setItem('queue', JSON.stringify(array))
            }
    }
    getLocalStorage() {
        const parseli = localStorage.getItem('queue')        
        return parseli;
    }
}

2021-11-23 18:08 UTC, Yurii97 commented on src/js/locale-stor.js
> +}
const obj1 = {
    name: "vaasya",
    vote: "8.3",
    votes: "12000000",
    popularity: "100,2",
    genre: "Western",
    about: "Four of the West’s most infamous outlaws assemble to steal a huge stash of gold from the most corrupt settlement of the gold rush towns. But not all goes to plan one is killed and the other three escapes with bags of gold hide out in the abandoned gold mine where they happen across another gang of three – who themselves were planning to hit the very same bank! As tensions rise, things go from bad to worse as they realise the bags of gold are filled with lead... they’ve been double crossed – but by who and how?", img: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/ci5A9TPmNajMxt1L8p4KlZ76sc9.jpg"
}
const obj2 = {
    name: "vaafya",
    vote: "8.3566",
    votes: "12000",
    popularity: "100,245",
    genre: "Western",
    about: "Four of the West’s most infamous outlaws assemble to steal a huge stash of gold from the most corrupt settlement of the gold rush towns. But not all goes to plan one is killed and the other three escapes with bags of gold hide out in the abandoned gold mine where they happen across another gang of three – who themselves were planning to hit the very same bank! As tensions rise, things go from bad to worse as they realise the bags of gold are filled with lead... they’ve been double crossed – but by who and how?", img: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/ci5A9TPmNajMxt1L8p4KlZ76sc9.jpg"
}
const obj3 = {
    name: "vaasya",
    vote: "8.3",
    votes: "12000000",
    popularity: "100,2",
    genre: "Western",
    about: "Four of the West’s most infamous outlaws assemble to steal a huge stash of gold from the most corrupt settlement of the gold rush towns. But not all goes to plan one is killed and the other three escapes with bags of gold hide out in the abandoned gold mine where they happen across another gang of three – who themselves were planning to hit the very same bank! As tensions rise, things go from bad to worse as they realise the bags of gold are filled with lead... they’ve been double crossed – but by who and how?", img: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/ci5A9TPmNajMxt1L8p4KlZ76sc9.jpg"
}

2021-11-23 18:08 UTC, Yurii97 commented on src/js/locale-stor.js
> +}
const localStoreQueue = new LocalStorQueue();

localStoreQueue.saveLocalStorage(obj1);
localStoreQueue.saveLocalStorage(obj2)
localStoreQueue.saveLocalStorage(obj3)
localStoreQueue.getLocalStorage();

2021-11-23 18:08 UTC, Yurii97 commented on src/partials-html/gallery.html
> +
не твій файл!

2021-11-23 18:36 UTC, Yurii97 requested changes
ВИДАЛИТИ ЦЮ ГІЛКУ

2021-11-23 18:47 UTC, Vladosik12333 commented
New PR

2021-11-23 18:47 UTC, closed without merging